#!/usr/bin/env python3
"""
Interactive Installation Wizard
Guides user through deployment with options
"""

import os
import sys
import subprocess
from pathlib import Path

class InstallWizard:
    def __init__(self):
        self.config = {}
        self.base_dir = Path(__file__).parent.absolute()

    def clear_screen(self):
        os.system('clear' if os.name != 'nt' else 'cls')

    def print_header(self):
        print("=" * 60)
        print("🇧🇩 National AI-Enabled Crop Health Advisory System")
        print("Interactive Installation Wizard")
        print("=" * 60)
        print()

    def ask_yes_no(self, question, default=True):
        while True:
            default_str = "Y/n" if default else "y/N"
            response = input(f"{question} [{default_str}]: ").strip().lower()
            if not response:
                return default
            if response in ['y', 'yes']:
                return True
            if response in ['n', 'no']:
                return False
            print("Please answer 'yes' or 'no'")

    def ask_input(self, question, default=""):
        if default:
            response = input(f"{question} [{default}]: ").strip()
            return response if response else default
        return input(f"{question}: ").strip()

    def run(self):
        self.clear_screen()
        self.print_header()

        print("Welcome! This wizard will guide you through deployment.")
        print()

        # Step 1: Environment
        print("📋 Step 1: Environment Configuration")
        print("-" * 40)

        self.config['environment'] = self.ask_input(
            "Environment", "production"
        )
        self.config['domain'] = self.ask_input(
            "Domain name", "cropadvisory.gov.bd"
        )
        self.config['admin_email'] = self.ask_input(
            "Admin email", "admin@cropadvisory.gov.bd"
        )

        print()

        # Step 2: Database
        print("🗄️  Step 2: Database Configuration")
        print("-" * 40)

        self.config['db_password'] = self.ask_input(
            "Database password", "change-me-in-production"
        )

        print()

        # Step 3: WhatsApp
        print("📱 Step 3: WhatsApp Integration (Optional)")
        print("-" * 40)

        if self.ask_yes_no("Enable WhatsApp integration?", False):
            self.config['whatsapp_token'] = self.ask_input(
                "WhatsApp API Token"
            )
            self.config['whatsapp_phone_id'] = self.ask_input(
                "WhatsApp Phone Number ID"
            )

        print()

        # Step 4: SSL
        print("🔒 Step 4: SSL Configuration")
        print("-" * 40)

        ssl_option = self.ask_yes_no(
            "Generate self-signed certificates? (No = use Let's Encrypt)", 
            True
        )
        self.config['self_signed_ssl'] = ssl_option

        print()

        # Step 5: Review
        print("📋 Step 5: Review Configuration")
        print("-" * 40)

        for key, value in self.config.items():
            if 'password' in key or 'token' in key:
                value = '*' * len(value)
            print(f"  {key}: {value}")

        print()

        if not self.ask_yes_no("Proceed with deployment?", True):
            print("Deployment cancelled.")
            return

        # Step 6: Deploy
        print()
        print("🚀 Starting deployment...")
        print("=" * 60)

        self.create_env_file()
        self.run_deployment()

    def create_env_file(self):
        """Create .env file from configuration"""
        env_content = f"""
# Auto-generated by installation wizard
ENVIRONMENT={self.config.get('environment', 'production')}
DOMAIN={self.config.get('domain', 'cropadvisory.gov.bd')}

# Database
DATABASE_URL=postgresql://postgres:{self.config.get('db_password', 'password')}@db:5432/crop_advisory

# Security
SECRET_KEY={os.urandom(32).hex()}

# WhatsApp
WHATSAPP_TOKEN={self.config.get('whatsapp_token', '')}
WHATSAPP_PHONE_NUMBER_ID={self.config.get('whatsapp_phone_id', '')}
VERIFY_TOKEN=crop_health_bot_{os.urandom(8).hex()}

# AI Model
CONFIDENCE_THRESHOLD=0.6
"""

        env_file = self.base_dir / "backend" / ".env"
        with open(env_file, 'w') as f:
            f.write(env_content.strip())

        print("✅ Created .env file")

    def run_deployment(self):
        """Run the deployment"""
        os.chdir(self.base_dir)

        # Run one-click deploy
        result = subprocess.run(
            ["./one_click_deploy.sh"],
            capture_output=False,
            text=True
        )

        if result.returncode == 0:
            print()
            print("=" * 60)
            print("🎉 Installation Complete!")
            print("=" * 60)
            print()
            print("Your system is now running at:")
            print(f"  https://{self.config.get('domain', 'localhost')}")
            print()
            print("Next steps:")
            print("  1. Configure your domain DNS")
            print("  2. Set up WhatsApp webhook")
            print("  3. Test the API endpoints")
            print("  4. Train your AI model with real data")
        else:
            print()
            print("❌ Deployment failed. Check logs for details.")

if __name__ == "__main__":
    wizard = InstallWizard()
    wizard.run()
